name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: pdm-project/setup-pdm@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: just ci-install
      - name: Run Ruff Linter
        run: just ci-ruff 
      - name: Run Sql Linter
        run: just ci-sql
      - name: Run MyPy
        run: just ci-mypy

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
          image: postgres:15
          ports:
            - "5432:5432"
          env:
            POSTGRES_DB: test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: pdm-project/setup-pdm@v3
      - name: Install PostgreSQL Driver
        run: |
          sudo apt-get install -y unixodbc-dev odbc-postgresql devscripts
          # Fix PostgreSQL driver paths
          sed --in-place 's/psqlodbca.so/\/usr\/lib\/x86_64-linux-gnu\/odbc\/psqlodbca.so/' /etc/odbcinst.ini
          sed --in-place 's/psqlodbcw.so/\/usr\/lib\/x86_64-linux-gnu\/odbc\/psqlodbcw.so/' /etc/odbcinst.ini
        shell: sudo bash {0}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: just install
      - name: Run Unit-tests
        run: just test
